
GET http://localhost:2000/viewvisitor
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTg4NjUzOWViMzNlMzU0NjE1MjkzNzEiLCJ1c2VybmFtZSI6ImZ6IiwicGFzc3dvcmQiOjEyMzQ1NiwiaWF0IjoxNzAzNDM5NjAzLCJleHAiOjE3MDM0NDMyMDN9.pNIP8wWiP1RgLRJlZJTscY5BDuBKc3e1wiwFkNvQDHo

####
POST http://localhost:2000/registeradmin
Content-Type: application/json

[
    {
        "username": "fz",
        "password": 123456
    }, 

    { 
        "username" : "az",
        "password" : 1234567
    }
    
]

###
//Admin issue visitor pass

POST http://localhost:2000/issuevisitorpass
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTg4NjUzOWViMzNlMzU0NjE1MjkzNzEiLCJ1c2VybmFtZSI6ImZ6IiwicGFzc3dvcmQiOjEyMzQ1NiwiaWF0IjoxNzAzNDQyNDE4LCJleHAiOjE3MDM0NDYwMTh9.X0PJ2PbWSxMboI8vVlD8VxPcGeOvudhY88TncVKOKtU

{
    "visitorId": "65887247d95fd4326c636288",
    "issuedBy": "fzi",
    "validUntil": "2023-10 23:59:59"
}


###
//Visitor to Retrieve Their Pass          //visitor ID
GET http://localhost:2000/retrievepass/65887247d95fd4326c636288



####
POST http://localhost:2000/login
Content-Type: application/json

{ 
    "username": "az",
    "password": 1234567

}

####
POST http://localhost:2000/registervisitor
Content-Type: application/json
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTg4NjUzOWViMzNlMzU0NjE1MjkzNzIiLCJ1c2VybmFtZSI6ImF6IiwicGFzc3dvcmQiOjEyMzQ1NjcsImlhdCI6MTcwMzQ0NDAwMSwiZXhwIjoxNzAzNDQ3NjAxfQ.MNIgxG75cRAiimypLBiw7G8RWajtpOG4bqrkLJm11HA
{
    "Name": "anis",
    "Phone_Number": "01234567890",
    "Address": "jalan permai",
    "Floor_Wing": "23k",
    "Whom_to_meet": "zana",
    "Reason_to_meet": "party"
}
